common:
  layout: demo
  css:
    site:
      - demos/highlight

  js:
    site:
      - lib/prettify

preload_images_with_jquery_preload_plugin:
  title: jQuery Preload Plugin Demo

  css:
    site:
      - demos/preload_images_with_jquery_preload_plugin

  js:
    cdn:
      - https://ajax.googleapis.com/ajax/libs/jquery/1.2.3/jquery.min

    site:
      - lib/jquery.preload
      - demos/preload_images_with_jquery_preload_plugin


get_hidden_element_width_with_jquery_actual_plugin:
  title: jQuery Actual Plugin Demo - Normal Usage

  css:
    site:
      - demos/get_hidden_element_width_with_jquery_actual_plugin

  js:
    cdn:
      - https://ajax.googleapis.com/ajax/libs/jquery/1.2.3/jquery.min

    site:
      - lib/jquery.actual
      - demos/get_hidden_element_width_with_jquery_actual_plugin


get_hidden_element_width_with_jquery_actual_plugin_with_css3pie:
  title: jQuery Actual Plugin Demo - with css3pie

  css:
    site:
      - demos/get_hidden_element_width_with_jquery_actual_plugin_with_css3pie

  js:
    cdn:
      - https://ajax.googleapis.com/ajax/libs/jquery/1.2.3/jquery.min

    site:
      - lib/jquery.actual
      - demos/get_hidden_element_width_with_jquery_actual_plugin_with_css3pie

hide_global_objects_in_javascript:
  title: jQuery Secret Plugin Demo

  css:
    site:
      - demos/hide_global_objects_in_javascript

  js:
    cdn:
      - https://ajax.googleapis.com/ajax/libs/jquery/1.3.0/jquery.min

    site:
      - lib/jquery.secret
      - demos/hide_global_objects_in_javascript


javascript_loose_coupling_with_jquery_queue_plugin:
  title: jQuery Queue Plugin Demo

  css:
    site:
      - demos/javascript_loose_coupling_with_jquery_queue_plugin

  js:
    cdn:
      - https://ajax.googleapis.com/ajax/libs/jquery/1.3.0/jquery.min

    site:
      - lib/jquery.queue
      - demos/javascript_loose_coupling_with_jquery_queue_plugin


centralize_html_dom_element_with_jquery_center_plugin:
  title: jQuery Center Plugin Demo

  css:
    site:
      - demos/centralize_html_dom_element_with_jquery_center_plugin

  js:
    cdn:
      - https://ajax.googleapis.com/ajax/libs/jquery/1.2.6/jquery.min

    site:
      - lib/jquery.center
      - demos/centralize_html_dom_element_with_jquery_center_plugin


jquery_blockui_alternative_with_jquery_msg_plugin:
  title: jQuery Center Plugin Demo

  css:
    site:
      - lib/jquery.msg
      - demos/jquery_blockui_alternative_with_jquery_msg_plugin

  js:
    cdn:
      - https://ajax.googleapis.com/ajax/libs/jquery/1.3.0/jquery.min

    site:
      - lib/jquery.center
      - lib/jquery.msg
      - demos/jquery_blockui_alternative_with_jquery_msg_plugin


google_image_search_style_image_alignment_with_jquery_atteeeeention_plugin:
  title: jQuery Atteeeeention Plugin Demo

  css:
    site:
      - demos/google_image_search_style_image_alignment_with_jquery_atteeeeention_plugin

  js:
    cdn:
      - https://ajax.googleapis.com/ajax/libs/jquery/1.2.6/jquery.min

    site:
      - lib/jquery.atteeeeention
      - demos/google_image_search_style_image_alignment_with_jquery_atteeeeention_plugin